LineLength:
  Max: 120
AllCops:
  TargetRubyVersion: 2.4
  Exclude:
    - 'spec/**/*'
    - 'bin/*'
  DisplayCopNames: true
Rails:
  Enabled: false
Documentation:
  Enabled: false
FrozenStringLiteralComment:
  Enabled: false
