language: ruby
cache: bundler

before_install:
  - "find /home/travis/.rvm/rubies -wholename '*default/bundler-*.gemspec' -delete"
  - rvm @global do gem uninstall bundler -a -x -I || true
  - gem install bundler -v '~> 1.10'

bundler_args: --without yard guard benchmarks
env: JRUBY_OPTS="$JRUBY_OPTS --debug"

gemfile:
  - gemfiles/oga.gemfile
  - gemfiles/nokogiri.gemfile

rvm:
  - 2.4
  - 2.5
  - 2.6
  - 2.7
  - ruby-head
  - jruby-9.2.8.0
  - truffleruby-head

matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-9.2.8.0
    - rvm: truffleruby-head
