language: ruby
before_install: gem install bundler
bundler_args: --without yard guard benchmarks
script: "rake spec"
rvm:
  - 2.0
  - 2.1
  - 2.2.4
  - 2.3.3
  - 2.4.2
  - ruby-head
matrix:
  allow_failures:
    - rvm: ruby-head
