language: ruby
before_install: gem install bundler
bundler_args: --without yard guard benchmarks
script: "rake spec"
env: JRUBY_OPTS="$JRUBY_OPTS --debug"
gemfile:
  - gemfiles/oga.gemfile
  - gemfiles/nokogiri.gemfile
gemfile:
  - gemfiles/oga.gemfile
  - gemfiles/nokogiri.gemfile
rvm:
  - 2.0
  - 2.1
  - 2.2.4
  - 2.3.3
  - 2.4.2
  - ruby-head
  - jruby-9.1.15.0
matrix:
  allow_failures:
    - rvm: ruby-head
  exclude:
    - rvm: 2.0
      gemfile: gemfiles/nokogiri.gemfile # Nokogiri doesn't support Ruby 2.0
